---
swagger: "2.0"
info:
  description: "blog"
  version: "1.0.0"
  title: "blog"
tags:
- name: "博客相关接口"
- name: "用户管理"
paths:
  /blog/query:
    get:
      tags:
      - "博客相关接口"
      operationId: "query"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Blog"
  /user/add:
    post:
      tags:
      - "用户管理"
      operationId: "addUser"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /user/delete:
    post:
      tags:
      - "用户管理"
      operationId: "deleteUser"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /user/query:
    get:
      tags:
      - "用户管理"
      operationId: "queryUser"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /user/queryAll:
    get:
      tags:
      - "用户管理"
      operationId: "queryAll"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /user/update:
    post:
      tags:
      - "用户管理"
      operationId: "updateUser"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/User"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
definitions:
  Blog:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      title:
        type: "string"
      content:
        type: "string"
      create_time:
        type: "integer"
        format: "int64"
      update_time:
        type: "integer"
        format: "int64"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      username:
        type: "string"
      password:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      sex:
        type: "string"
      age:
        type: "integer"
        format: "int32"
      createTime:
        type: "integer"
        format: "int64"
      updateTime:
        type: "integer"
        format: "int64"
